// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web;

#nullable disable

namespace web.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("web.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverUserName");

                    b.HasIndex("SenderUserName");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("web.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Salt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("web.Models.Message", b =>
                {
                    b.HasOne("web.Models.User", "Receiver")
                        .WithMany("Inbox")
                        .HasForeignKey("ReceiverUserName");

                    b.HasOne("web.Models.User", "Sender")
                        .WithMany("Sent")
                        .HasForeignKey("SenderUserName");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("web.Models.User", b =>
                {
                    b.Navigation("Inbox");

                    b.Navigation("Sent");
                });
#pragma warning restore 612, 618
        }
    }
}
